import { newbooCoverAsset } from "./assets.mjs";
import { compileRenderPlan } from "./motion-core.mjs";

const nonEmpty = (value) => {
  const text = String(value ?? "").trim();
  return text || "";
};

const cleanList = (value) => (
  Array.isArray(value)
    ? value.map((item) => nonEmpty(item)).filter(Boolean)
    : []
);

const firstSentence = (value) => {
  const text = nonEmpty(value).replace(/\s+/g, " ");
  if (!text) return "";
  const match = text.match(/^(.+?[.!?])(?:\s|$)/);
  return nonEmpty(match?.[1] || text);
};

const truncate = (value, max = 360) => {
  const text = nonEmpty(value).replace(/\s+/g, " ");
  if (text.length <= max) return text;
  const cut = text.slice(0, Math.max(1, max - 1)).replace(/\s+\S*$/, "").trim();
  return `${cut || text.slice(0, max - 1)}…`;
};

const unwrapBook = (input) => {
  if (!input || typeof input !== "object" || Array.isArray(input)) {
    throw new Error("Newboo book payload must be an object");
  }
  if (input.book && typeof input.book === "object" && !Array.isArray(input.book)) {
    return input.book;
  }
  return input;
};

const coverSlot = (book, explicitCoverId) => {
  if (nonEmpty(explicitCoverId)) {
    return { id: nonEmpty(explicitCoverId), url: nonEmpty(book.cover_url) };
  }
  for (const suffix of ["", "_2", "_3", "_4"]) {
    const id = nonEmpty(book[`cover_id${suffix}`]);
    const url = nonEmpty(book[`cover_url${suffix}`]);
    if (id || url) return { id, url };
  }
  return { id: "", url: nonEmpty(book.cover_url) };
};

/**
 * Convert the canonical Newboo BookRepositoryRow / BookResponse shape into the
 * small immutable payload consumed by deterministic ad templates.
 *
 * No copy is generated by AI here. Missing ad copy falls back only to existing
 * book metadata (subtitle / description / title) through deterministic rules.
 */
export const newbooBookToRenderPayload = (input, options = {}) => {
  const book = unwrapBook(input);
  const storageBookId = nonEmpty(options.storageBookId || book.book_id || book.public_id);
  const publicId = nonEmpty(book.public_id || book.book_id);
  const title = nonEmpty(book.title);
  if (!title) throw new Error("Newboo book title is required");

  const description = nonEmpty(book.description);
  const subtitle = nonEmpty(book.subtitle);
  const releaseNote = nonEmpty(book.release_note);
  const author = nonEmpty(book.author_name);
  const genres = cleanList(book.genres);
  const tags = cleanList(book.tags);
  const fandoms = cleanList(book.fandoms);
  const selectedCover = coverSlot(book, options.coverId);

  const suppliedQuote = nonEmpty(options.quote || options.excerpt);
  const fallbackBody = description || releaseNote || subtitle || title;
  const hook = truncate(
    options.hook || subtitle || firstSentence(description) || title,
    Number(options.hookMaxChars) || 150,
  );
  const quote = truncate(
    suppliedQuote || fallbackBody,
    Number(options.quoteMaxChars) || 420,
  );
  const quoteLabel = nonEmpty(
    options.quoteLabel || (suppliedQuote ? "EXCERPT" : description ? "ABOUT THE BOOK" : "BOOK"),
  );
  const genre = nonEmpty(
    options.genre || genres[0] || book.catalog_section || tags[0] || "BOOK",
  );
  const cta = nonEmpty(options.cta || "READ NOW");

  const asset = selectedCover.id && storageBookId
    ? newbooCoverAsset({
        bookId: storageBookId,
        coverId: selectedCover.id,
        target: options.coverTarget || "source",
        bucket: options.bucket,
        etag: options.etag,
        version: options.version,
      })
    : null;

  return Object.freeze({
    kind: "book-render-payload",
    version: 1,
    source: "newboo",
    id: publicId || storageBookId || title,
    storageBookId: storageBookId || undefined,
    title,
    subtitle,
    author,
    genre,
    hook,
    quote,
    quoteLabel,
    cta,
    cover: Object.freeze({
      asset,
      publicUrl: selectedCover.url || undefined,
      background: nonEmpty(options.coverBackground || "#e8e2d3"),
      ink: nonEmpty(options.coverInk || "#10263a"),
      accent: nonEmpty(options.coverAccent || "#e2673f"),
    }),
    metadata: Object.freeze({
      description,
      originalTitle: nonEmpty(book.original_title),
      languageOriginal: nonEmpty(book.language_original),
      languageTranslation: nonEmpty(book.language_translation),
      year: Number.isFinite(Number(book.year)) ? Number(book.year) : undefined,
      catalogSection: nonEmpty(book.catalog_section),
      ageRating: nonEmpty(book.age_rating),
      statusLabel: nonEmpty(book.status_label),
      genres: Object.freeze(genres),
      tags: Object.freeze(tags),
      fandoms: Object.freeze(fandoms),
      sourceUrl: nonEmpty(book.source_url),
    }),
  });
};

export const compileBookAdV0RenderPlan = (payload, options = {}) => {
  if (!payload || payload.kind !== "book-render-payload") {
    throw new Error("book-render-payload is required");
  }
  return compileRenderPlan({
    id: nonEmpty(options.id || `book-ad-v0:${payload.id}`),
    fps: Number(options.fps) || 30,
    aspect: options.aspect || "9:16",
    background: options.background || "#07131f",
    scenes: [
      { id: "hook", recipe: "hook", seconds: 3 },
      { id: "quote", recipe: "quote", seconds: 5 },
      { id: "cover", recipe: "cover", seconds: 4 },
      { id: "cta", recipe: "cta", seconds: 3, transitionFrames: 0 },
    ],
  });
};

export const createBookAdV0Job = (input, options = {}) => {
  const payload = input?.kind === "book-render-payload"
    ? input
    : newbooBookToRenderPayload(input, options);
  const plan = compileBookAdV0RenderPlan(payload, options);
  return Object.freeze({
    kind: "book-render-job",
    version: 1,
    template: "book-ad-v0",
    payload,
    plan,
  });
};

const bytesToBase64 = (bytes) => {
  if (typeof Buffer !== "undefined") return Buffer.from(bytes).toString("base64");
  let binary = "";
  for (const byte of bytes) binary += String.fromCharCode(byte);
  return btoa(binary);
};

const base64ToBytes = (value) => {
  if (typeof Buffer !== "undefined") return new Uint8Array(Buffer.from(value, "base64"));
  const binary = atob(value);
  return Uint8Array.from(binary, (char) => char.charCodeAt(0));
};

export const encodeBookRenderJob = (job) => {
  const json = JSON.stringify(job);
  return bytesToBase64(new TextEncoder().encode(json))
    .replace(/\+/g, "-")
    .replace(/\//g, "_")
    .replace(/=+$/g, "");
};

export const decodeBookRenderJob = (value) => {
  const token = nonEmpty(value);
  if (!token) return null;
  const base64 = token.replace(/-/g, "+").replace(/_/g, "/");
  const padded = base64 + "=".repeat((4 - (base64.length % 4)) % 4);
  const json = new TextDecoder().decode(base64ToBytes(padded));
  const job = JSON.parse(json);
  if (!job || job.kind !== "book-render-job" || !job.payload) {
    throw new Error("invalid book render job");
  }
  return job;
};
